### ISSUE TITLE
FormHandler : submit stuck after a-data-function eval

### ISSUE THREAD

**Issue by AlexisDESANTO** [Atom-Fundation/Atom#23]
Can't submit form manually after in a-data-function eval.

Expected : release listener after eval.

**Comment by tdelavoux** [comment]
Corrected in [f989e37](https://github.com/Atom-Fundation/Atom/commit/f989e37565c6516680b119c9c5b59d510a614b3e) for main branch. Must be implemented in chore/vanilla-js-global branch

**Comment by tdelavoux** [comment]
Natively fixed in Vanilla JS version
