### ISSUE TITLE
Collapse do not mask padding

### ISSUE THREAD

**Issue by tdelavoux** [Atom-Fundation/Atom#41]
Using collapse with padding on content do not entirely close the element : 
![image](https://user-images.githubusercontent.com/31383617/210387648-865fe582-91f6-4723-8034-7fb24967f02f.png)

How to reproduce
```
<div class="a-panel a-panel-primary a-panel-collapsable">
	<div class="a-panel-header a-collapsable" collapse-target="#content1">Panel Title</div>
	<div class="a-panel-content" id="content1">Panel content</div>
</div>
```

**Comment by nathanaelhoun** [comment]
After some debugging, it appears to be because `max-height`  changes `height`  but not `padding` nor `border`.          
As the `a-panel-content` has some padding, the element doesn't collapse fully. [Relevant SO](https://stackoverflow.com/a/20827604/16242651).

Searching for a fix.
